
services:
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "3000:3000"
    depends_on:
      - middle_api
    networks:
      - myinternalnetwork
    
  middle_api:
    build:
      context: ./my_middle_API
    ports:
      - "8000:8000"
    networks:
      - myinternalnetwork

  db:
    build: ./storage/postgres
    environment:
      POSTGRES_DB: aqar_scraper
      POSTGRES_USER: scraper_user
      POSTGRES_PASSWORD: scraper_password
    volumes:
      - /root/s_locator/storage/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - myinternalnetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_pgadmin_password
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - myinternalnetwork


networks:
  myinternalnetwork:
