name: Deploy Dev

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual build and deploy'


jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      env:
        DEV_FIREBASE_SA: ${{ secrets.DEV_FIREBASE_SA }}
        DEV_SECRETS_GMAP: ${{ secrets.DEV_SECRETS_GMAP }}
        DEV_SECRETS_FIREBASE: ${{ secrets.DEV_SECRETS_FIREBASE }}
        FRONTEND_ENV: ${{ secrets.FRONTEND_ENV }}
        DEV_SECRET_DATABASE_ENV: ${{ secrets.DEV_SECRET_DATABASE_ENV }}
        DEV_GCLOUD_CONSOLE_SA: ${{ secrets.DEV_GCLOUD_CONSOLE_SA }}
        DEV_SECRET_STRIPE: ${{ secrets.DEV_SECRET_STRIPE }}
      with:
        host: '37.27.195.216'
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        envs: DEV_FIREBASE_SA,DEV_SECRETS_GMAP,DEV_SECRETS_FIREBASE,FRONTEND_ENV,DEV_SECRET_DATABASE_ENV, DEV_GCLOUD_CONSOLE_SA, DEV_SECRET_STRIPE
        script: |
          set -x  # Enable debug mode
          set -e  # Exit on error
          
          echo "Starting deployment process..."

          cd ..
          cd ..
          cd ..
          cd ..
          cd ..
          if [ -d "s_locator" ]; then
            cd s_locator
            docker compose down
            echo "Docker compose down completed."
            
            cd ..
            rm -rf s_locator
            echo "Removed existing s_locator directory."
          fi
          
          # Clone the repository and update submodules
          git config --global user.email "ci@example.com"
          git config --global user.name "Github actions"
          git clone --recursive https://github.com/abdullahalhoothy/s_locator.git &&
          cd s_locator &&
          git submodule update --remote --recursive &&
          git submodule foreach 'git checkout dev && git pull origin dev'
          echo "Repository cloned and submodules updated."
          
          # Create secrets directory if it doesn't exist
          mkdir -p my_middle_API/secrets
          mkdir -p storage/secrets
          echo "Secret directories created."
          
          # Create secret files
          echo '${{ secrets.DEV_FIREBASE_SA }}' > my_middle_API/secrets/secret_dev-s-locator-SA.json
          echo '${{ secrets.DEV_SECRETS_GMAP }}' > my_middle_API/secrets/secrets_gmap.json
          echo '${{ secrets.DEV_SECRETS_FIREBASE }}' > my_middle_API/secrets/secrets_firebase.json
          echo '${{ secrets.DEV_SECRET_DATABASE_ENV }}' > storage/secrets/secrets_database.env
          echo '${{ secrets.FRONTEND_ENV }}' > FrontEnd/.env
          echo '${{ secrets.DEV_GCLOUD_CONSOLE_SA }}' > my_middle_API/secrets/weighty-gasket-437422-h6-a9caa84da98d.json
          echo '${{ secrets.DEV_SECRET_STRIPE }}' > my_middle_API/secrets/secret_stripe.json

          echo "Secret files created."
          
          # Replace values in files
          sed -i 's|"REACT_APP_API_URL": "http://localhost:8000/fastapi"|"REACT_APP_API_URL": "http://37.27.195.216:8000/fastapi"|g' FrontEnd/src/urls.json
          sed -i 's|enable_CORS_url: str = "http://localhost:3000"|enable_CORS_url: str = "http://37.27.195.216:3000"|g' my_middle_API/config_factory.py
          sed -i 's|uvicorn.run(app, host="localhost", port=8000)|uvicorn.run(app, host="0.0.0.0", port=8000, reload=True)|g' my_middle_API/run_apps.py
          echo "Configuration files updated."
         
          # Install jq
          apt-get update && apt-get install -y jq
          echo "jq installed."
          
          # For Backup
          touch /backup.sh
          cp ./backup.sh /backup.sh
          chmod 777 backup_setup.sh
          ./backup_setup.sh
          echo "Backup setup completed."
          
          # Build and run Docker containers
          docker compose build
          echo "Docker compose build completed."
          
          docker compose up -d
          echo "Docker compose up completed."
          
          # Get container ID of frontend container and install Google Cloud SDK
          FRONTEND_CONTAINER_ID=$(docker ps | grep frontend | awk '{print $1}')
          echo "Frontend container ID: $FRONTEND_CONTAINER_ID"
          
          # Retrieve population data on the container
          docker exec $FRONTEND_CONTAINER_ID bash -c "
            echo 'deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main' | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list &&
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - &&
            apt-get update &&
            apt-get install -y google-cloud-sdk &&
            mkdir -p dist/data/population_json_files/ &&
            gsutil -m cp -r gs://s-locator/misc/population_json_files dist/data/population_json_files/
          "
          echo "Population data retrieval completed."
          
          echo "Deployment process finished."
